# Generated by Django 4.2.6 on 2023-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('container_title', models.CharField(max_length=100)),
                ('container_des', models.TextField()),
                ('container_url', models.CharField(max_length=100)),
                ('container_image', models.ImageField(upload_to='\\container')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100)),
                ('post_des', models.TextField()),
                ('post_url', models.CharField(max_length=200)),
                ('post_image', models.ImageField(upload_to='\\posts')),
            ],
        ),
    ]
